name: Github Action Deploy

on:
  push:
    branches:
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check branches
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        echo "master"

    - name: check branches
      if: ${{ github.ref == 'refs/heads/develop' }}
      run: |
        echo "develop"

    - name: Cloning the repo
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, sodium, zip
        coverage: none

    - name: Create .env file for composer
      run: |
        cp .env.example .env
        composer install --prefer-dist --no-interaction --no-suggest --ignore-platform-reqs

    # - name: Setup Nodejs 14.x
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: '14.x'

    # - name: npm install
    #   run: |
    #     npm install
    #     npm run development

    - name: Begin - Set remote file permission to github-runner
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: ./ansible/deploy-master-begin.yml
        directory: ./
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
          [webservers]
          ${{secrets.SSH_SERVER}}

          [webservers:vars]
          ansible_user=${{secrets.SSH_USER}}
          ansible_sudo_pass=${{secrets.SSH_USER_PASS}}

    - name: Deploy to server exclude git, ansible & .env
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      with:
        flags: '-avz --exclude=".git*" --exclude .env --exclude=".ansible_*" --exclude="ansible*"'
        options: ''
        ssh_options: '-p ${{secrets.SSH_PORT}}'
        src: '.'
        dest: '${{secrets.SSH_USER}}@${{secrets.SSH_SERVER}}:/var/www/github_action/'

    - name: End - Set remove file permission to www-data, clear laravel cache
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: ./ansible/deploy-master-end.yml
        directory: ./
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
          [webservers]
          ${{secrets.SSH_SERVER}}

          [webservers:vars]
          ansible_user=${{secrets.SSH_USER}}
          ansible_sudo_pass=${{secrets.SSH_USER_PASS}}
